#' Plot augmented fieldbook design
#'
#' Plot fieldbook sketches for augmented experimental designs generated by
#' `design_augmented()`.
#'
#' @param data Fieldbook data frame from an augmented design.
#' @param factor Character. Column used to color experimental units. Default is
#'   `"type"` when available.
#' @param fill Character vector. Column or columns used as labels inside each
#'   experimental unit. Default is `"plots"`.
#' @param xlab Character. Optional x axis title.
#' @param ylab Character. Optional y axis title.
#' @param glab Character. Optional legend title.
#'
#' @details
#' This function is intended for augmented designs with checks and entries.
#' It uses:
#'
#' \itemize{
#'   \item `cols` as the x axis.
#'   \item `block` as the y axis when available.
#'   \item `type` to distinguish checks, tests and empty plots.
#' }
#'
#' Empty plots are shown in grey when `type` is `NA`.
#'
#' @return A `ggplot` object.
#'
#' @import dplyr
#' @import ggplot2
#'
#' @export

plot_augmented_design <- function(data,
                                  factor = NA,
                                  fill = "plots",
                                  xlab = NULL,
                                  ylab = NULL,
                                  glab = NULL) {
  
  # -------------------------------------------------------------------------
  # Checks ------------------------------------------------------------------
  # -------------------------------------------------------------------------
  
  if(!is.data.frame(data)) {
    stop("'data' must be a data frame.")
  }
  
  required_cols <- c("plots", "entry", "type", "block", "rows", "cols")
  
  missing_cols <- setdiff(required_cols, names(data))
  
  if(length(missing_cols) > 0) {
    stop(
      "Missing required columns for augmented plot: ",
      paste(missing_cols, collapse = ", ")
    )
  }
  
  if(is.na(factor) || is.null(factor) || factor == "") {
    factor <- if("type" %in% names(data)) {
      "type"
    } else {
      "checks"
    }
  }
  
  if(!factor %in% names(data)) {
    stop(
      "Column selected in 'factor' was not found in data. Available columns: ",
      paste(names(data), collapse = ", ")
    )
  }
  
  if(is.null(fill) || length(fill) == 0 || any(is.na(fill)) || fill[1] == "") {
    fill <- "plots"
  }
  
  if(!all(fill %in% names(data))) {
    stop(
      "Column selected in 'fill' was not found in data. Available columns: ",
      paste(names(data), collapse = ", ")
    )
  }
  
  # -------------------------------------------------------------------------
  # Helper: labels -----------------------------------------------------------
  # -------------------------------------------------------------------------
  
  make_label <- function(data, fill) {
    
    labels <- lapply(fill, function(x) {
      
      if(x == "ntreat") {
        ifelse(is.na(data[[x]]), "", paste0("T", data[[x]]))
      } else {
        ifelse(is.na(data[[x]]), "", as.character(data[[x]]))
      }
      
    })
    
    do.call(paste, c(labels, sep = "\n"))
    
  }
  
  # -------------------------------------------------------------------------
  # Data preparation ---------------------------------------------------------
  # -------------------------------------------------------------------------
  
  data_plot <- data %>%
    dplyr::mutate(
      .plot_type = dplyr::case_when(
        is.na(.data$type) ~ "empty",
        .data$type == "" ~ "empty",
        TRUE ~ as.character(.data$type)
      ),
      .plot_factor = dplyr::case_when(
        is.na(.data[[factor]]) ~ "empty",
        as.character(.data[[factor]]) == "" ~ "empty",
        TRUE ~ as.character(.data[[factor]])
      ),
      .plot_factor = as.factor(.data$.plot_factor),
      .plot_label = make_label(data = ., fill = fill)
    )
  
  # -------------------------------------------------------------------------
  # Labels and style ---------------------------------------------------------
  # -------------------------------------------------------------------------
  
  if(is.null(xlab)) {
    xlab <- "columns"
  }
  
  if(is.null(ylab)) {
    ylab <- "blocks"
  }
  
  if(is.null(glab)) {
    glab <- factor
  }
  
  text_size <- dplyr::case_when(
    length(fill) == 1 ~ 3.2,
    length(fill) == 2 ~ 2.8,
    TRUE ~ 2.3
  )
  
  line_height <- dplyr::case_when(
    length(fill) == 1 ~ 1.05,
    length(fill) == 2 ~ 1.00,
    TRUE ~ 0.95
  )
  
  # -------------------------------------------------------------------------
  # Colors ------------------------------------------------------------------
  # -------------------------------------------------------------------------
  
  if(factor == "type") {
    
    color_values <- c(
      check = "#4E79A7",
      test = "#59A14F",
      empty = "#D9D9D9"
    )
    
    factor_levels <- unique(as.character(data_plot$.plot_factor))
    
    color_values <- color_values[names(color_values) %in% factor_levels]
    
    extra_levels <- setdiff(factor_levels, names(color_values))
    
    if(length(extra_levels) > 0) {
      
      extra_cols <- grDevices::colorRampPalette(
        c("#86CD80", "#F4CB8C", "#F3BB00", "#0198CD", "#FE6673")
      )(length(extra_levels))
      
      names(extra_cols) <- extra_levels
      
      color_values <- c(color_values, extra_cols)
      
    }
    
  } else {
    
    factor_levels <- levels(data_plot$.plot_factor)
    
    color_values <- grDevices::colorRampPalette(
      c(
        "#86CD80",
        "#F4CB8C",
        "#F3BB00",
        "#0198CD",
        "#FE6673"
      )
    )(length(factor_levels))
    
    names(color_values) <- factor_levels
    
  }
  
  # -------------------------------------------------------------------------
  # Block boxes --------------------------------------------------------------
  # -------------------------------------------------------------------------
  
  block_boxes <- data_plot %>%
    dplyr::group_by(.data$block) %>%
    dplyr::summarise(
      xmin = min(.data$cols, na.rm = TRUE) - 0.5,
      xmax = max(.data$cols, na.rm = TRUE) + 0.5,
      ymin = min(.data$block, na.rm = TRUE) - 0.5,
      ymax = max(.data$block, na.rm = TRUE) + 0.5,
      .groups = "drop"
    )
  
  # -------------------------------------------------------------------------
  # Plot --------------------------------------------------------------------
  # -------------------------------------------------------------------------
  
  plot <- data_plot %>%
    dplyr::arrange(.data$block, .data$cols) %>%
    ggplot2::ggplot(
      ggplot2::aes(
        x = .data$cols,
        y = .data$block,
        fill = .data$.plot_factor
      )
    ) +
    ggplot2::geom_tile(
      color = "grey25",
      linewidth = 0.35
    ) +
    ggplot2::geom_rect(
      data = block_boxes,
      ggplot2::aes(
        xmin = .data$xmin,
        xmax = .data$xmax,
        ymin = .data$ymin,
        ymax = .data$ymax
      ),
      inherit.aes = FALSE,
      fill = NA,
      color = "black",
      linewidth = 0.55
    ) +
    ggplot2::geom_text(
      ggplot2::aes(label = .data$.plot_label),
      size = text_size,
      lineheight = line_height,
      fontface = "plain",
      color = "black"
    ) +
    ggplot2::scale_y_continuous(
      expand = c(0, 0),
      trans = "reverse",
      breaks = sort(unique(data_plot$block))
    ) +
    ggplot2::scale_x_continuous(
      expand = c(0, 0),
      breaks = sort(unique(data_plot$cols))
    ) +
    ggplot2::scale_fill_manual(values = color_values) +
    ggplot2::labs(
      x = xlab,
      y = ylab,
      fill = glab
    ) +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(
      legend.position = "top",
      legend.title = ggplot2::element_text(face = "bold"),
      legend.text = ggplot2::element_text(size = 9),
      panel.grid = ggplot2::element_blank(),
      axis.title = ggplot2::element_text(face = "bold"),
      axis.text = ggplot2::element_text(color = "grey25"),
      plot.margin = ggplot2::margin(6, 6, 6, 6)
    )
  
  return(plot)
  
}